define("DS/ENONewWidget/ENONewWidget_en", {});
define("DS/ENONewWidget/assets/nls/ENONewFacetNls", {
    defaultFacetCreate: "Properties",
    classificationFacet: "Part name library/bookmarks",
    revisionFacet: "Revision"
});
define("DS/ENONewWidget/assets/nls/ENONewWidgetNls", {
    newContentLabel: "New Content",
    CreateNew: "Create New ",
    "new": "New",
    locked: "Locked",
    unlocked: "Unlocked",
    createBtn: "Create another",
    createCloseBtn: "Create",
    closeBtn: "Cancel",
    creatingButton: "Creating",
    repeatCheckbox: "Repeat",
    loading: "Loading",
    previousBtn: "Previous",
    nextBtn: "Next",
    saveBtn: "Save",
    saveBtnLoading: "Saving",
    saveSettingsTitle: "Save",
    confirmsaveSettingsMsg: "Do you really want to deploy this 3D Part Template for Type {type} ?",
    confirmsaveSuccessMsg: "3D Part Template selection correctly saved for Type {type}",
    confirmsaveErrorMsg: "Empty 3D Part Template not allowed for Type {type}",
    collapseExtension: "Show less",
    expandExtension: "Show more",
    Type: "Type",
    SecurityContext: "Credentials",
    ObjCreationFailed: "Creating the object failed.",
    cantCreateObject: "You cannot create this object",
    cantCreateObject1: "You cannot create this type of object",
    contactYourAdmin: "Contact your administrator.",
    ENONEW_ERROR_0002_Title: "You cannot create this type of object",
    ENONEW_ERROR_0002_Subtitle: "Contact your administrator.",
    ENONEW_ERROR_0003_Subtitle: "The object initialization failed. Contact your administrator.",
    ENONEW_ERROR_0003_Msg: "The object initialization business logic script might not be correct.",
    ENONEW_ERROR_1001_Title: "Creating the object failed.",
    ENONEW_ERROR_1001_Subtitle: "Contact your administrator to verify that the PLMIdentificationInitialization business logic script is correct.",
    ENONEW_ERROR_1002_Title: "Creating the object failed.",
    ENONEW_ERROR_1002_Subtitle: "Contact your administrator to verify that the PLMAttributesValuationFinalization business logic script is correct.",
    ENONEW_ERROR_1003_Title: "Creating the object failed.",
    ENONEW_ERROR_1003_Subtitle: "Verify that you specified valid values for the following properties, or contact your administrator.",
    ENONEW_ERROR_4005_Title: "You cannot insert this object type under the selected object",
    ENONEW_ERROR_5001_Subtitle: "Verify that you are using the correct credentials.",
    ENONEW_ERROR_5001_Msg: "You may not have the required access role in the target collaborative space to create this type of object.",
    InvalidAccess_Subtitle: "Refresh your browser, and verify that you are using the correct credentials.",
    InvalidAccess_Msg: "You may not have the required access role in the target collaborative space to create this type of object.",
    NetworkError_Title: "The server disconnected unexpectedly.",
    NetworkError_Subtitle: "Contact your administrator for support.",
    ENONEW_ERROR_5002_Title: "Object's identifier set is already used for another component.",
    ENONEW_ERROR_5002_Subtitle: "Please set unique identifier.",
    ENONEW_ERROR_5003_Title: "The value you specified for one of the attributes is already used for another object.",
    ENONEW_ERROR_5003_Subtitle: "Contact your administrator to know which attribute value must be unique, and choose another value  for this attribute.",
    ENONEW_ERROR_8001_Title: "The {type} has been created with errors.",
    ENONEW_ERROR_8001_Subtitle: "Modify this object in an appropriate app to fix these failed operations:",
    CLASS_IS_NOT_NULL: "Part name library cannot be empty！",
    CLASS_GETID_FAIL: "Failed to retrieve library information, please contact the administrator！",
    Btn_OK: "Submit",
    Btn_Cancel: "Cancel",
    Export_Type_Label: "Export Revision",
    Export_Type_Title: "Select Revision",
    Export_Type_IsRequire:"Export Revision Is Require !",
    Export_Type_LastRevision: "Last Revision",
    Export_Type_Placeholder: "Please select the export type",
    Export_Type_LastRevisionRelease: "Last Release Revision",
    Export_Export_Loading: "Exporting in progress, please wait 5-10 minutes",
    SyncMBOMToMDMModel_Tilte:"Select factory code",
    SyncMBOMToMDMModel_IsRequire:"The factory code is mandatory.",
    SyncMBOMToMDMModel_Loading:"Syncing in progress. Please wait for 5 to 10 minutes...",
    SyncMBOMToMDMModel_Label: "Synchronize to MDM",
    SyncMBOMToMDMModel_Placeholder: "Please select the factory.",
    SyncMBOMToMDMModel_1021:"1021-HEFEI JFSeat Plant",
    SyncMBOMToMDMModel_1031:"1031-CHANGZHOU JFSeat Plant",
    SyncMBOMToMDMModel_1071:"1071-NIBONG JFSeat Plant",
    SyncMBOMToMDMModel_1091:"1091-BEIJING JFSeat Plant",
    SyncMBOMToMDMModel_1121:"1121-FUZHOU JFSeat Plant",
    SyncMBOMToMDMModel_1151:"1151-WUHU JFSeat Plant",
    SyncMBOMToMDMModel_1161:"1161-YIWU JFSeat Plant",
    SyncMBOMToMDMModel_9061:"9061-GRAMMER TIANJIN Plant",
    SyncMBOMToMDMModel_9071:"9071-GRAMMER CHANGCHUN Plant",
    SyncMBOMToMDMModel_2031:"2031-Thailand Plant",
    SyncMBOMToMDMModel_1211:"1211-CHONGQING  JFSeat Plant",
    SyncMBOMToMDMModel_2021:"2021-Cheb GJAS Plant"
});