<%@ page import="java.io.InputStream" %>
<%@ page import="java.io.OutputStream" %>
<%@ page import="java.io.FileOutputStream" %>

<%@ page import="com.matrixone.apps.common.CommonDocument" %>
<%@ page import="matrix.db.FileList" %>
<%@ page import="com.matrixone.apps.domain.DomainObject" %>
<%@ page import="com.matrixone.apps.domain.util.MqlUtil" %>
<%@ page import="matrix.db.Context" %>
<%@ page import="com.matrixone.apps.domain.util.ContextUtil" %>
<%@ page import="com.matrixone.apps.cpd.json.JSONObject" %>
<%@ page import="com.matrixone.apps.framework.ui.UICache" %>
<%@ page import="com.matrixone.apps.domain.DomainRelationship" %>
<%@ page import="com.matrixone.apps.framework.ui.UIUtil" %>
<%@ page import="matrix.util.StringList" %>

<%@include file = "../common/emxNavigatorTopErrorInclude.inc"%>
<%@include file = "ECMDesignTopInclude.inc"%>
<%@include file = "../common/enoviaCSRFTokenValidation.inc"%>


<jsp:useBean id="indentedTableBean" class="com.matrixone.apps.framework.ui.UITableIndented" scope="session"/>
<jsp:useBean id="formBean" scope="session" class="com.matrixone.apps.common.util.FormBean"/>

<%
    //Context contextDB = (matrix.db.Context)request.getAttribute("context");
    JSONObject josn =new JSONObject();
    try {

        String fileName = emxGetParameter(request,"fileName");
        System.out.println("into Aer >>>>>>>>>>fileName"+fileName);
        int fakePathIndex =fileName.lastIndexOf("fakepath")+9;

        if(fileName.contains("fakepath")){
            fileName = fileName.substring(fakePathIndex);
        }
        System.out.println("into Aer >>>>>>>>>>2222fileName"+fileName);
        String objectId        = emxGetParameter(request, "objectId");
        System.out.println("into Aer >>>>>>>>>>objectId"+objectId);
        //String fileNameExt[] = fileName.split("\\.");
        //String fileExt = fileNameExt[1];
        InputStream inputStream = request.getInputStream();
        String strTempDir= context.createWorkspace();
        System.out.println("into Aer >>>>>>>>>>strTempDir"+strTempDir);
        OutputStream outputStream = new FileOutputStream(strTempDir+"/"+fileName);
        int byteCount = 0;
        byte[] bytes = new byte[1024];
        while ((byteCount = inputStream.read(bytes)) != -1)
        {
            outputStream.write(bytes, 0, byteCount);

        }
        inputStream.close();
        outputStream.close();
        String owner=context.getUser();
        ContextUtil.pushContext(context);
        DomainObject DocEcr= DomainObject.newInstance(context,objectId);


        String docid="";
        String doctitle="";
        StringList docidlist=DocEcr.getInfoList(context,"from[Active Version].to.id");






        java.io.File file=new java.io.File(strTempDir+"/"+fileName);

        DocEcr.checkinFile(context, false, true, "", "generic", file.getName(), file.getParent());



        String sObjGeneratorName = UICache.getObjectGenerator(context, "type_Document", "");
        String sName = DomainObject.getAutoGeneratedName(context, sObjGeneratorName, "");

        CommonDocument cDoc = new CommonDocument();
        cDoc.createObject(context, DomainObject.TYPE_DOCUMENT, sName, "1", "Version", context.getVault().getName());
        cDoc.setAttributeValue(context, "Title", file.getName());
        cDoc.setAttributeValue(context, "Is Version Object", "True");
        cDoc.setAttributeValue(context, "JF_DocReceiptConfirmation", "Y");

        DomainRelationship.connect(context,DocEcr,"Active Version",cDoc);
        DomainRelationship.connect(context,DocEcr,"Latest Version",cDoc);
        cDoc.setAttributeValue(context,"Originator",owner);
        cDoc.setOwner(context,owner);

        josn.put("state","0");
        josn.put("id",cDoc.getId(context));
        josn.put("title", file.getName());
    } catch (Exception e) {
        e.printStackTrace();
        josn.put("state","1");
        josn.put("error",e.getMessage());
    }finally {
        ContextUtil.popContext(context);
    }
    out.clear();
    out.write( josn.toString());
%>