import com.matrixone.apps.domain.DomainConstants;
import com.matrixone.apps.domain.DomainObject;
import com.matrixone.apps.domain.util.FrameworkException;
import com.matrixone.apps.domain.util.FrameworkUtil;
import com.matrixone.apps.domain.util.MapList;
import com.matrixone.apps.domain.util.MqlUtil;
import matrix.db.Context;
import matrix.util.StringList;

import java.util.Map;
import java.util.Properties;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.locks.ReentrantLock;
import com.matrixone.apps.framework.ui.UIUtil;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class JF_VPMT_mxJPO {
    private static final Logger log = LoggerFactory.getLogger(JF_VPMT_mxJPO.class);
    String TYPE_JFDATATRANSMISSION = "type_JFPartNumberG";
    String ATTRIBUTE_PARTNUMBER = "EnterpriseExtension.V_PartNumber";
    String ATTRIBUTE_PARTTYPE = "JF_VPMReference.JF_PartType";
    private static JF_VPMT_mxJPO instance =null;
    private ConcurrentHashMap<String, ReentrantLock> locks;
    private ConcurrentHashMap<String, Long> sequenceNumbers;
    public  String sRetryCount = "5";
    public  String sRetryDelay = "1000";
    String partTypes = "M,E,F,P,U,D,X,T,C";
    private JF_VPMT_mxJPO(Context context){
        try {
            log.info("create JF_VPMT_mxJPO");
            StringList partypelist = FrameworkUtil.getRanges(context, ATTRIBUTE_PARTTYPE);
            locks = new ConcurrentHashMap<>();
            sequenceNumbers = new ConcurrentHashMap<>();
            for (String partype : partypelist) {
                if(UIUtil.isNotNullAndNotEmpty(partype)) {
                    locks.put(partype, new ReentrantLock());
                    sequenceNumbers.put(partype, 0L);
                }
            }
            //竞品类型
            locks.put("BM", new ReentrantLock());
            sequenceNumbers.put("BM", 0L);
        }catch (Exception e){
            e.printStackTrace();
        }
    }
    public static JF_VPMT_mxJPO getInstance(Context context) {
        if(instance==null){
            synchronized (JF_VPMT_mxJPO.class){
                if(instance==null) {
                    instance = new JF_VPMT_mxJPO(context);
                }
            }
        }
        return instance;
    }

    public String autoName_old(Context context, DomainObject part,String code) throws FrameworkException {
        ReentrantLock lock = locks.get(code);
        lock.lock();
        String partName = "";
        try {
            //partName = DomainObject.getAutoGeneratedName(context, TYPE_JFDATATRANSMISSION + code, "");
            String val = MqlUtil.mqlCommand(context,"print bus 'eService Number Generator' '"+TYPE_JFDATATRANSMISSION + code+"' '' select attribute[eService Next Number].value dump;");
            String prefixval = MqlUtil.mqlCommand(context,"print bus 'eService Object Generator' '"+TYPE_JFDATATRANSMISSION + code+"' '' select attribute[eService Name Prefix].value dump;");
            partName = prefixval+val;
            int len = val.length();
            int nextNum = Integer.parseInt(val);
            nextNum += 1;
            String nextNumber  = String.format("%"+len+"s", nextNum+"").replace(' ', '0');
            MqlUtil.mqlCommand(context,"mod bus 'eService Number Generator' '"+TYPE_JFDATATRANSMISSION + code+"' ''  'eService Next Number' "+nextNumber+";");
        }catch (Exception e){
            log.error(e.getMessage());
            e.printStackTrace();
        }finally {
            lock.unlock();
        }
        return partName;
        //part.setAttributeValue(context,ATTRIBUTE_PARTNUMBER,partName);
    }

    public String autoName(Context context, DomainObject part, String code) throws FrameworkException {
        ReentrantLock lock = locks.get(code);
        String partName = "";
        try {
            if (lock.tryLock(10, TimeUnit.SECONDS)) { // 设置超时时间为10秒
                try {
                    // 业务逻辑
//                   String val = MqlUtil.mqlCommand(context,"print bus 'eService Number Generator' '"+TYPE_JFDATATRANSMISSION + code+"' '' select attribute[eService Next Number].value dump;");
                    String prefixval = MqlUtil.mqlCommand(context,"print bus 'eService Object Generator' '"+TYPE_JFDATATRANSMISSION + code+"' '' select attribute[eService Name Prefix].value dump;");
             /*       partName = prefixval+val;
                    int len = val.length();
                    int nextNum = Integer.parseInt(val);
                    nextNum += 1;
                    String nextNumber  = String.format("%"+len+"s", nextNum+"").replace(' ', '0');
                    MqlUtil.mqlCommand(context,"mod bus 'eService Number Generator' '"+TYPE_JFDATATRANSMISSION + code+"' ''  'eService Next Number' "+nextNumber+";");
*/
                   String val = eServiceNumberGenerator(context,code);
                    partName = prefixval+val;
                    log.info("partName:{}",partName);
                } finally {
                    lock.unlock();
                }
            } else {
                log.error("获取锁超时，code: {}", code);
                // 处理超时逻辑，例如重试或返回错误信息
            }
        } catch (InterruptedException e) {
            log.error("线程被中断", e);
            Thread.currentThread().interrupt(); // 恢复中断状态
        }
        return partName;
    }
    /*
     * @description:基于TCL取号,可以避免多cas下高并发取号重复
     * @author: caipan
     * @date: 2026/1/30 16:28:12
     * @param: * @param[1] context
     * @param[2] sNumberGeneratorId
     * @return:
     **/
    public String eServiceNumberGenerator(Context context,String code){
        String where = "name=='"+TYPE_JFDATATRANSMISSION + code+"'";
        String sNumberGeneratorId = "";
        String strResult="";
        try {
           MapList list = DomainObject.findObjects(context,"eService Number Generator","*",where,JF_Util_mxJPO.basicBolistSel());
           if(list.size()>0) {
               sNumberGeneratorId = UIUtil.getValue((Map)list.get(0), DomainConstants.SELECT_ID);
               String mql = "exec program eServicecommonGetNextNumber.tcl " + sRetryCount + " " + sRetryDelay + " " + sNumberGeneratorId;
               strResult = MqlUtil.mqlCommand(context, false, mql, true);
           }
        }catch (Exception e){
            e.printStackTrace();
        }

        return  strResult;
    }


}
